### ISSUE TITLE
BAND submodule / software should include citation guidelines of BAND framework

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/bandframework#62]
Provide citation guideline within each piece of software per "Citing the BAND Framework" in [BAND Readme](https://github.com/bandframework/bandframework/blob/main/README.md)

**Comment by wildsm** [comment]
Were you thinking  adding this to

-  the SDK https://github.com/bandframework/bandframework/blob/main/resources/sdkpolicies/bandsdk.md

- the template https://github.com/bandframework/bandframework/blob/main/resources/sdkpolicies/template.md

- both?

The template has the greatest visibility since it gets reused,  but I am worried about maintainability... is the expectation that every package need to update their SDK compatibility file with every change to band framework authorship?

Adding to SDK may be simplest (duplicates only the bibtex). Would we increment the SDK version number any time the bibtex changes?

**Comment by mosesyhc** [comment]
Maintainability is a real concern.  My impression from the discussion is that visibility for the citation of BAND framework can be improved.  

Would it be simpler if only a pointer to the citation block (in either the SDK or the template) is required?  But it would mean pointing to the most current bibtex always.

As of now, it might be possible to have each package update the SDK compatibility.  But I agree that maintenance will become more difficult as more submodules are linked.  One way is to have an SDK review before BAND vX.XX.

**Comment by wildsm** [comment]
I do not see any way to pull in an external in a markdown file, which would have been the preferred way (i.e., have a standalone bib file).

I have added the citation to the actual sdk and added a line to the template.

The submodule packages QGP_Bayes, SAMBA, surmise have not yet been updated with this, but everything else has.

**Comment by mosesyhc** [comment]
I have seen a solution in the past (e.g., using markdown-helper  https://github.com/github/markup/issues/1159#issuecomment-368516799.)  But it requires pre-compiling.

I think the addition to the SDK and template work fine, as we don't anticipate frequent bib changes.

I am quite confident we can make it happen for QGP_Bayes, SAMBA, and surmise.

**Comment by wildsm** [comment]
closed with #61

**Comment by wildsm** [comment]
closed with #61 61
